apiVersion: v1
kind: Service
metadata:
  name: go-book-api-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 4545
    targetPort: 4545
    protocol: TCP
  selector:
    app: go-book-api
